INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Albania', 'Leke', 'ALL', 'Lek', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('America', 'Dollars', 'USD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Afghanistan', 'Afghanis', 'AFN', '؋', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Argentina', 'Pesos', 'ARS', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Aruba', 'Guilders', 'AWG', 'ƒ', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Australia', 'Dollars', 'AUD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Azerbaijan', 'New Manats', 'AZN', 'ман', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Bahamas', 'Dollars', 'BSD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Barbados', 'Dollars', 'BBD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Belarus', 'Rubles', 'BYR', 'p.', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Belgium', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Beliz', 'Dollars', 'BZD', 'BZ$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Bermuda', 'Dollars', 'BMD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Bolivia', 'Bolivianos', 'BOB', '$b', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Botswana', 'Pula', 'BWP', 'P', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Bulgaria', 'Leva', 'BGN', 'лв', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Brazil', 'Reais', 'BRL', 'R$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Britain (United Kingdom)', 'Pounds', 'GBP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Brunei Darussalam', 'Dollars', 'BND', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Cambodia', 'Riels', 'KHR', '៛', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Canada', 'Dollars', 'CAD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Cayman Islands', 'Dollars', 'KYD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Chile', 'Pesos', 'CLP', '$', 1);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('China', 'Yuan Renminbi', 'CNY', '¥', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Colombia', 'Pesos', 'COP', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Costa Rica', 'Colón', 'CRC', '₡', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Croatia', 'Kuna', 'HRK', 'kn', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Cuba', 'Pesos', 'CUP', '₱', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Cyprus', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Czech Republic', 'Koruny', 'CZK', 'Kč', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Denmark', 'Kroner', 'DKK', 'kr', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Dominican Republic', 'Pesos', 'DOP ', 'RD$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('East Caribbean', 'Dollars', 'XCD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Egypt', 'Pounds', 'EGP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('El Salvador', 'Colones', 'SVC', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('England (United Kingdom)', 'Pounds', 'GBP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Euro', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Falkland Islands', 'Pounds', 'FKP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Fiji', 'Dollars', 'FJD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('France', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Ghana', 'Cedis', 'GHC', '¢', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Gibraltar', 'Pounds', 'GIP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Greece', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Guatemala', 'Quetzales', 'GTQ', 'Q', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Guernsey', 'Pounds', 'GGP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Guyana', 'Dollars', 'GYD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Holland (Netherlands)', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Honduras', 'Lempiras', 'HNL', 'L', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Hong Kong', 'Dollars', 'HKD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Hungary', 'Forint', 'HUF', 'Ft', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Iceland', 'Kronur', 'ISK', 'kr', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('India', 'Rupees', 'INR', 'Rp', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Indonesia', 'Rupiahs', 'IDR', 'Rp', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Iran', 'Rials', 'IRR', '﷼', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Ireland', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Isle of Man', 'Pounds', 'IMP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Israel', 'New Shekels', 'ILS', '₪', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Italy', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Jamaica', 'Dollars', 'JMD', 'J$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Japan', 'Yen', 'JPY', '¥', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Jersey', 'Pounds', 'JEP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Kazakhstan', 'Tenge', 'KZT', 'лв', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Korea (North)', 'Won', 'KPW', '₩', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Korea (South)', 'Won', 'KRW', '₩', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Kyrgyzstan', 'Soms', 'KGS', 'лв', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Laos', 'Kips', 'LAK', '₭', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Latvia', 'Lati', 'LVL', 'Ls', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Lebanon', 'Pounds', 'LBP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Liberia', 'Dollars', 'LRD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Lithuania', 'Litai', 'LTL', 'Lt', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Luxembourg', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Macedonia', 'Denars', 'MKD', 'ден', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Malaysia', 'Ringgits', 'MYR', 'RM', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Malta', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Mauritius', 'Rupees', 'MUR', '₨', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Mexico', 'Pesos', 'MXN', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Mongolia', 'Tugriks', 'MNT', '₮', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Mozambique', 'Meticais', 'MZN', 'MT', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Namibia', 'Dollars', 'NAD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Nepal', 'Rupees', 'NPR', '₨', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Netherlands Antilles', 'Guilders', 'ANG', 'ƒ', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Netherlands', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('New Zealand', 'Dollars', 'NZD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Nicaragua', 'Cordobas', 'NIO', 'C$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Nigeria', 'Nairas', 'NGN', '₦', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('North Korea', 'Won', 'KPW', '₩', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Norway', 'Krone', 'NOK', 'kr', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Oman', 'Rials', 'OMR', '﷼', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Pakistan', 'Rupees', 'PKR', '₨', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Panama', 'Balboa', 'PAB', 'B/.', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Paraguay', 'Guarani', 'PYG', 'Gs', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Peru', 'Nuevos Soles', 'PEN', 'S/.', 1);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Philippines', 'Pesos', 'PHP', 'Php', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Poland', 'Zlotych', 'PLN', 'zł', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Qatar', 'Rials', 'QAR', '﷼', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Romania', 'New Lei', 'RON', 'lei', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Russia', 'Rubles', 'RUB', 'руб', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Saint Helena', 'Pounds', 'SHP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Saudi Arabia', 'Riyals', 'SAR', '﷼', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Serbia', 'Dinars', 'RSD', 'Дин.', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Seychelles', 'Rupees', 'SCR', '₨', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Singapore', 'Dollars', 'SGD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Slovenia', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Solomon Islands', 'Dollars', 'SBD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Somalia', 'Shillings', 'SOS', 'S', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('South Africa', 'Rand', 'ZAR', 'R', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('South Korea', 'Won', 'KRW', '₩', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Spain', 'Euro', 'EUR', '€', 1);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Sri Lanka', 'Rupees', 'LKR', '₨', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Sweden', 'Kronor', 'SEK', 'kr', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Switzerland', 'Francs', 'CHF', 'CHF', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Suri`name`', 'Dollars', 'SRD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Syria', 'Pounds', 'SYP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Taiwan', 'New Dollars', 'TWD', 'NT$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Thailand', 'Baht', 'THB', '฿', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Trinidad and Tobago', 'Dollars', 'TTD', 'TT$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Turkey', 'Lira', 'TRY', 'TL', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Turkey', 'Liras', 'TRL', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Tuvalu', 'Dollars', 'TVD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Ukraine', 'Hryvnia', 'UAH', '₴', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('United Kingdom', 'Pounds', 'GBP', '£', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('United States of America', 'Dollars', 'USD', '$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Uruguay', 'Pesos', 'UYU', '$U', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Uzbekistan', 'Sums', 'UZS', 'лв', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Vatican City', 'Euro', 'EUR', '€', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Venezuela', 'Bolivares Soberanos', 'VES', 'Bs.S', 1);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Vietnam', 'Dong', 'VND', '₫', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Yemen', 'Rials', 'YER', '﷼', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$', 0);
INSERT INTO `countries` (`name`, `currency`, `iso`, `symbol`, `active`) VALUES ('India', 'Rupees', 'INR', '₹', 0);
